---
certbot_package: certbot-nginx
nginx_conf_file: /etc/nginx/nginx.conf
nginx_service: nginx
email_address: hsjarbin@redhat.com
guid_domain: example.opentlc.com

letsencrypt_certdir: /etc/letsencrypt/live
tower_cert_dir: /etc/tower/
